# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-assignment"
client_id = "47cb9ef385a065b2dc8ac109ed4a96c7"
application_url = "https://ebony-attacked-woods-guide.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_script_tags,write_script_tags,read_themes,write_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://ebony-attacked-woods-guide.trycloudflare.com/auth/callback",
  "https://ebony-attacked-woods-guide.trycloudflare.com/auth/shopify/callback",
  "https://ebony-attacked-woods-guide.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-kk-store1.myshopify.com"
